yaml
name: CDK Deploy

on:
  pull_request:
    branches:
      - develop
      - stg
  push:
    branches:
      - develop
      - stg

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

  test:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test  # テストが成功した場合にのみデプロイを実行
    if: github.event_name == 'push'  # push イベントのときにのみ実行

    steps:
      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-1'  # 使用する AWS リージョン
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            npm run deploy:dev
          elif [[ "${{ github.ref }}" == "refs/heads/stg" ]]; then
            npm run deploy:stg
          fi
